#!/bin/bash

# Azure DevOps Test Data Generator using Azure CLI
# Generates test work items and sprints for testing the board view

set -e  # Exit on error

# ============ CONFIGURATION ============
ORG_URL="${ADO_ORG_URL:-https://dev.azure.com/dammyboss}"
PROJECT="${ADO_PROJECT:-test}"
TEAM="${ADO_TEAM:-test Team}"
TEST_TAG="TestData-AutoGenerated"

# ============ COLORS ============
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# ============ FUNCTIONS ============

print_header() {
    echo ""
    echo "╔════════════════════════════════════════╗"
    echo "║   Azure DevOps Test Data Generator    ║"
    echo "╚════════════════════════════════════════╝"
    echo ""
}

check_az_cli() {
    if ! command -v az &> /dev/null; then
        echo -e "${RED}✗ Azure CLI not found${NC}"
        echo ""
        echo "Please install Azure CLI first:"
        echo "  brew update && brew install azure-cli"
        echo ""
        echo "Or visit: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
        exit 1
    fi

    # Check if devops extension is installed
    if ! az extension list | grep -q "azure-devops"; then
        echo -e "${YELLOW}⚠ Azure DevOps extension not installed${NC}"
        echo "Installing azure-devops extension..."
        az extension add --name azure-devops
    fi

    echo -e "${GREEN}✓ Azure CLI and DevOps extension ready${NC}"
}

check_authentication() {
    echo ""
    echo "Checking authentication..."

    # Try to list projects to verify authentication
    if ! az devops project list --org "$ORG_URL" &> /dev/null; then
        echo -e "${YELLOW}⚠ Not authenticated to Azure DevOps${NC}"
        echo ""
        echo "Please authenticate using one of these methods:"
        echo ""
        echo "Option 1: Login interactively"
        echo "  az login"
        echo ""
        echo "Option 2: Use a Personal Access Token (PAT)"
        echo "  export AZURE_DEVOPS_EXT_PAT='your-pat-token'"
        echo ""
        echo "To create a PAT:"
        echo "  1. Go to $ORG_URL/_usersSettings/tokens"
        echo "  2. Create a token with 'Work Items (Read, Write)' scope"
        echo "  3. Copy the token and run: export AZURE_DEVOPS_EXT_PAT='your-token'"
        echo ""
        exit 1
    fi

    echo -e "${GREEN}✓ Authenticated to Azure DevOps${NC}"
}

configure_defaults() {
    echo ""
    echo "Configuring defaults..."
    az devops configure --defaults organization="$ORG_URL" project="$PROJECT"
    echo -e "${GREEN}✓ Defaults configured${NC}"
    echo "  Organization: $ORG_URL"
    echo "  Project: $PROJECT"
    echo "  Team: $TEAM"
}

get_date_offset() {
    local days=$1
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS - handle negative days properly
        if [ $days -lt 0 ]; then
            date -v${days}d +%Y-%m-%d
        else
            date -v+${days}d +%Y-%m-%d
        fi
    else
        # Linux
        date -d "$days days" +%Y-%m-%d
    fi
}

create_iterations() {
    echo ""
    echo "🏗️  Creating test sprints..."
    echo ""

    # Clear temp file
    rm -f /tmp/ado_iterations.txt

    # Sprint schedule (days offset from today)
    declare -a sprints=(
        "Test Sprint 1:-44:-30:Past"
        "Test Sprint 2:-30:-16:Past"
        "Test Sprint 3:-7:7:CURRENT"
        "Test Sprint 4:8:22:Future"
        "Test Sprint 5:22:36:Future"
    )

    for sprint_data in "${sprints[@]}"; do
        IFS=':' read -r name start_offset end_offset status <<< "$sprint_data"

        start_date=$(get_date_offset "$start_offset")
        end_date=$(get_date_offset "$end_offset")

        # Create iteration path
        iteration_path="$PROJECT\\$name"

        if [ "$status" == "CURRENT" ]; then
            echo -e "  ${GREEN}🟢 Creating: $name (CURRENT)${NC}"
        else
            echo -e "  ⚪ Creating: $name ($status)"
        fi
        echo "     Dates: $start_date to $end_date"

        # Create iteration using Azure CLI
        result=$(az boards iteration project create \
            --name "$name" \
            --start-date "$start_date" \
            --finish-date "$end_date" \
            --project "$PROJECT" \
            --org "$ORG_URL" \
            --output json 2>&1)

        if [ $? -eq 0 ]; then
            echo -e "     ${GREEN}✓ Created iteration${NC}"
            # Store iteration info for work item creation
            echo "$iteration_path|$start_date|$end_date|$status" >> /tmp/ado_iterations.txt
        else
            # Check if it already exists
            if echo "$result" | grep -q "already exists"; then
                echo -e "     ${YELLOW}⚠ Iteration already exists${NC}"
                echo "$iteration_path|$start_date|$end_date|$status" >> /tmp/ado_iterations.txt
            else
                echo -e "     ${RED}✗ Failed: $(echo "$result" | head -1)${NC}"
            fi
        fi

        echo ""
    done
}

create_work_items() {
    echo ""
    echo "📝 Creating work items..."

    local total_created=0
    local item_index=1

    # Work item types to create per sprint
    declare -a work_item_types=("User Story" "User Story" "User Story" "Bug" "Task")

    while IFS='|' read -r iteration_path start_date end_date status; do
        sprint_name=$(basename "$iteration_path")

        echo ""
        if [ "$status" == "CURRENT" ]; then
            echo -e "  ${GREEN}🟢 Sprint: $sprint_name${NC}"
        else
            echo "     Sprint: $sprint_name"
        fi

        for wi_type in "${work_item_types[@]}"; do
            title="$wi_type: $sprint_name - Item $item_index"

            # Create description based on type
            if [ "$wi_type" == "User Story" ]; then
                description="<h3>User Story: $sprint_name - Item $item_index</h3><p>As a user, I want to test the board view with iteration filters, so that I can verify the functionality works correctly.</p><ul><li>Sprint: $sprint_name</li><li>Type: $wi_type</li><li>Index: $item_index</li></ul>"
                acceptance_criteria="<h4>Acceptance Criteria:</h4><ul><li><strong>Given</strong> a user is viewing the board</li><li><strong>When</strong> they filter by $sprint_name</li><li><strong>Then</strong> this work item should appear in the results</li></ul>"
            elif [ "$wi_type" == "Bug" ]; then
                description="<h3>Bug: $sprint_name - Item $item_index</h3><p><strong>Steps to Reproduce:</strong></p><ol><li>Open the application</li><li>Navigate to the test page</li><li>Observe the issue</li></ol><p><strong>Expected Result:</strong> Feature should work correctly</p>"
                acceptance_criteria=""
            else  # Task
                description="<h3>Task: $sprint_name - Item $item_index</h3><p>This is a test task for $sprint_name. It demonstrates how tasks appear on the board and can be filtered by iteration.</p>"
                acceptance_criteria=""
            fi

            # Create work item
            echo "     Creating: $title"

            if [ "$wi_type" == "User Story" ]; then
                work_item_id=$(az boards work-item create \
                    --type "$wi_type" \
                    --title "$title" \
                    --description "$description" \
                    --iteration "$iteration_path" \
                    --fields "Microsoft.VSTS.Common.AcceptanceCriteria=$acceptance_criteria" "System.Tags=$TEST_TAG" \
                    --output tsv --query id 2>&1)
            else
                work_item_id=$(az boards work-item create \
                    --type "$wi_type" \
                    --title "$title" \
                    --description "$description" \
                    --iteration "$iteration_path" \
                    --fields "System.Tags=$TEST_TAG" \
                    --output tsv --query id 2>&1)
            fi

            if [[ $work_item_id =~ ^[0-9]+$ ]]; then
                echo -e "     ${GREEN}✓ Created #$work_item_id${NC}"
                ((total_created++))
            else
                echo -e "     ${RED}✗ Failed: $work_item_id${NC}"
            fi

            ((item_index++))
            sleep 0.2  # Small delay to avoid rate limiting
        done
    done < /tmp/ado_iterations.txt

    echo ""
    echo -e "${GREEN}✅ Total work items created: $total_created${NC}"

    # Cleanup temp file
    rm -f /tmp/ado_iterations.txt
}

cleanup_work_items() {
    echo ""
    echo "🔍 Finding all work items with tag: $TEST_TAG..."

    # Query for work items with the test tag
    work_item_ids=$(az boards query \
        --wiql "SELECT [System.Id] FROM WorkItems WHERE [System.Tags] CONTAINS '$TEST_TAG' AND [System.TeamProject] = '$PROJECT'" \
        --output tsv --query "[].id" 2>&1)

    if [ -z "$work_item_ids" ]; then
        echo "  No test work items found"
        return
    fi

    # Convert to array
    IFS=$'\n' read -d '' -r -a ids <<< "$work_item_ids" || true
    count=${#ids[@]}

    echo "  Found $count test work items"
    echo ""
    echo -e "${YELLOW}⚠️  This will permanently delete $count work items!${NC}"
    echo "  Waiting 3 seconds... (Press Ctrl+C to cancel)"
    sleep 3

    echo ""
    echo "🗑️  Deleting work items..."

    local deleted=0
    for id in "${ids[@]}"; do
        if az boards work-item delete --id "$id" --yes &> /dev/null; then
            echo -e "  ${GREEN}✓ Deleted work item #$id${NC}"
            ((deleted++))
        else
            echo -e "  ${RED}✗ Failed to delete #$id${NC}"
        fi
        sleep 0.1
    done

    echo ""
    echo -e "${GREEN}✅ Deleted $deleted work items${NC}"
}

show_help() {
    echo "Usage: $0 [create|cleanup|help]"
    echo ""
    echo "Commands:"
    echo "  create   - Create test sprints and work items"
    echo "  cleanup  - Delete all test work items"
    echo "  help     - Show this help message"
    echo ""
    echo "Environment Variables:"
    echo "  ADO_ORG_URL   - Azure DevOps organization URL (default: https://dev.azure.com/dammyboss)"
    echo "  ADO_PROJECT   - Project name (default: test)"
    echo "  ADO_TEAM      - Team name (default: test Team)"
    echo ""
}

# ============ MAIN ============

print_header

case "${1:-help}" in
    create)
        echo "Configuration:"
        echo "  Organization: $ORG_URL"
        echo "  Project: $PROJECT"
        echo "  Team: $TEAM"
        echo "  Tag: $TEST_TAG"

        check_az_cli
        check_authentication
        configure_defaults
        create_iterations
        create_work_items

        echo ""
        echo "╔════════════════════════════════════════╗"
        echo "║          Test Data Created!            ║"
        echo "╚════════════════════════════════════════╝"
        echo ""
        echo "💡 To clean up, run:"
        echo "   $0 cleanup"
        ;;

    cleanup)
        check_az_cli
        check_authentication
        configure_defaults
        cleanup_work_items

        echo ""
        echo "╔════════════════════════════════════════╗"
        echo "║        Cleanup Complete!               ║"
        echo "╚════════════════════════════════════════╝"
        ;;

    help|*)
        show_help
        ;;
esac
