#!/bin/bash

# Test Data Generator Runner
# This script helps run the test data generator with your VS Code extension settings

echo "╔════════════════════════════════════════╗"
echo "║   Azure DevOps Test Data Generator    ║"
echo "║         Configuration Helper           ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "This script needs your Azure DevOps configuration."
echo ""
echo "You have two options:"
echo ""
echo "Option 1: Create a Personal Access Token (PAT)"
echo "  1. Go to https://dev.azure.com/dammyboss/_usersSettings/tokens"
echo "  2. Click 'New Token'"
echo "  3. Give it a name (e.g., 'Test Data Generator')"
echo "  4. Select scopes: Work Items (Read, Write)"
echo "  5. Click 'Create' and copy the token"
echo ""
echo "Option 2: Use existing OAuth token from VS Code extension"
echo "  Note: OAuth tokens from VS Code are stored in secure storage"
echo "  and cannot be easily extracted for use in standalone scripts."
echo "  We recommend Option 1 for this script."
echo ""
echo "To run the script with your PAT token:"
echo ""
echo "  export ADO_ORG_URL='https://dev.azure.com/dammyboss'"
echo "  export ADO_PROJECT='test'"
echo "  export ADO_TEAM='test Team'"
echo "  export ADO_PAT='your-pat-token-here'"
echo "  node scripts/generate-test-data.js create"
echo ""
echo "Or run it in one line:"
echo ""
echo "  ADO_ORG_URL='https://dev.azure.com/dammyboss' \\"
echo "  ADO_PROJECT='test' \\"
echo "  ADO_TEAM='test Team' \\"
echo "  ADO_PAT='your-pat-token-here' \\"
echo "  node scripts/generate-test-data.js create"
echo ""
